/**
 * LITEVM — Language Strings (English + Bahasa Indonesia)
 * Loaded after config.js, before page-specific JS.
 * Exposes App.t(key), App.setLang(lang), App.render().
 */
(function () {
  'use strict';

  const LANG = {
    en: {
      // --- index.html (Registration) ---
      'title-register': 'LITEVM — Visitor Registration',
      'header-title-register': 'Visitor Registration',
      'header-subtitle-register': 'Pre-register for quick entry',
      'step-details': 'Details',
      'step-photos': 'Photos',
      'step-submit': 'Submit',
      'your-details': 'Your Details',
      'your-details-subtitle': 'Please fill in your information below',
      'label-full-name': 'Full Name',
      'label-id-number': 'ID / Passport Number',
      'label-company': 'Company Name',
      'label-destination': 'Destination',
      'label-visitation-date': 'Visitation Date',
      'label-phone': 'Hand Phone Number',
      'label-email': 'Email Address',
      'placeholder-full-name': 'e.g. Ahmad bin Ismail',
      'placeholder-id-number': 'e.g. 880101-01-1234',
      'placeholder-company': 'e.g. ABC Sdn Bhd',
      'placeholder-destination-loading': 'Loading destinations...',
      'placeholder-destination-select': 'Select destination',
      'placeholder-phone': 'e.g. +60 12-345 6789',
      'placeholder-email': 'e.g. ahmad@example.com',
      'hint-destination': 'Which office are you visiting today?',
      'hint-visitation-date': 'Select the date you plan to visit',
      'hint-phone': 'You will receive your visitor number via phone',
      'btn-continue-photos': 'Continue → Photos',
      'btn-subtitle-fill': '(fill all fields to continue)',
      'btn-subtitle-tap': 'Tap to continue',
      // Step 2 - Photos
      'header-capture-photos': 'Capture Photos',
      'take-your-photos': 'Take Your Photos',
      'take-your-photos-subtitle': 'Please capture your ID document and a selfie. Both are required for entry.',
      'camera-denied': 'Camera access was denied. Please use the upload option instead.',
      'label-id-photo': 'ID Photo (Passport / IC)',
      'label-selfie': 'Selfie (Face Photo)',
      'tap-to-capture': 'Tap to capture',
      'initializing-camera': 'Initializing camera...',
      'btn-open-camera': 'Open Camera',
      'btn-upload': 'Upload',
      'btn-capture': 'Capture',
      'btn-retake': 'Retake',
      'btn-cancel': 'Cancel',
      'processing-photo': 'Processing photo...',
      'btn-review-submit': 'Review & Submit',
      'btn-subtitle-capture': '(capture both photos to continue)',
      'btn-subtitle-review': 'Review your information',
      // Step 3 - Review
      'header-review-submit': 'Review & Submit',
      'confirm-your-details': 'Confirm Your Details',
      'confirm-details-subtitle': 'Please review all information before submitting.',
      'personal-information': 'Personal Information',
      'review-label-name': 'Full Name',
      'review-label-id': 'ID / Passport',
      'review-label-company': 'Company',
      'review-label-destination': 'Destination',
      'review-label-visitation-date': 'Visitation Date',
      'review-label-phone': 'Phone',
      'review-label-email': 'Email',
      'section-photos': 'Photos',
      'review-label-id-photo': 'ID Photo',
      'review-label-selfie': 'Selfie',
      'not-captured': 'Not captured',
      'captured': 'Captured ✓',
      'consent-notice': 'By submitting, you consent to having your data and photos stored for visitor management purposes.',
      'btn-submit-registration': 'Submit Registration',
      // Step 4 - Confirmation
      'registration-complete': 'Registration Complete!',
      'registration-complete-subtitle': 'Your details have been submitted and recorded.',
      'show-qr-at-entrance': 'Show this QR code at the entrance',
      'your-visitor-number': 'Your Visitor Number',
      'email-confirmation': 'Email Confirmation',
      'email-confirmation-text': 'A confirmation email will be sent to your inbox shortly.',
      'next-steps': 'Next Steps',
      'next-step-1': 'Check your email within 2 minutes',
      'next-step-2': 'Show QR code at the entrance',
      'next-step-3': 'Guard will verify and grant access',
      'data-encrypted-secure': 'Your data is encrypted and secure',
      'btn-done': 'Done',
      // Loading & Error
      'submitting': 'Submitting...',
      'submitting-subtext': 'Please wait while we process your registration',
      'submission-failed': 'Submission Failed',
      'error-occurred': 'An error occurred. Please try again.',
      'btn-retry': 'Retry',
      'btn-cancel-error': 'Cancel',
      // Validation
      'err-full-name': 'Please enter your full name',
      'err-id-number': 'Please enter a valid ID or passport number',
      'err-id-format': 'Only letters, numbers, hyphens allowed',
      'err-company': 'Please enter your company name',
      'err-phone': 'Please enter a valid phone number (e.g. +60 12-345 6789)',
      'err-email-empty': 'Please enter your email address',
      'err-email-format': 'Please enter a valid email address',
      'err-destination': 'Please select a destination',
      'err-visitation-date': 'Please select a visitation date',
      'err-visitation-past': 'Visitation date cannot be in the past',
      // Destinations
      'loading-destinations': 'Loading destinations...',
      'no-destinations': 'No destinations available',
      'no-destinations-configured': 'No destinations configured',
      'retrying-destinations': 'Retrying...',
      'failed-to-load': 'Failed to load',
      'failed-load-destinations': 'Failed to load destinations. ',
      'tap-to-retry': 'Tap to retry',
      // Offline
      'offline-message': 'You are offline. Please check your connection.',
      // Privacy
      'privacy-footer': 'Your information is securely stored. Data is used only for visitor management purposes.',
      // Photo error messages
      'photo-too-large': 'Photo is too large. Maximum size is 5MB.',
      'err-capture-both-photos': 'Please capture both photos before submitting.',
      'err-fill-all-fields': 'Please fill all required fields correctly.',
      'err-offline-submit': 'You are offline. Please check your internet connection and try again.',
      'err-api-not-configured': 'API endpoint not configured. Please contact the administrator.',
      'err-unexpected-response': 'Unexpected response from server. Please try again.',
      'err-submission-failed': 'Submission failed. Please try again.',
      'err-request-timeout': 'Request timed out. Please check your connection and try again.',
      'err-connection-failed': 'Connection failed. This may be a browser security restriction. Try again or use a different browser.',
      'err-network': 'Network error. Please check your connection and try again.',
      'err-card-not-found': 'Card number not found.',
      'err-no-match-today': 'No match found for today. Make sure the number is correct.',
      'err-visitor-number-format': 'Visitor numbers follow the format V-YYYYMMDD-NNN (e.g. V-20250622-001). Please check the number and try again.',
      'err-failed-update-status': 'Failed to update status. Please try again.',
      'err-failed-load-destinations': 'Failed to load destinations.',
      // --- verify.html (Guard Portal) ---
      'title-verify': 'LITEVM — Guard Portal',
      'header-title-verify': 'LITEVM — Guard Portal',
      'header-subtitle-verify': 'Verify visitor check-in',
      'nav-visitor-registration': '← Visitor Registration',
      'nav-reports': '📋 Reports',
      'guard-portal': 'Guard Portal',
      'enter-pin': 'Enter PIN to access',
      'placeholder-pin': 'Enter PIN',
      'invalid-pin': 'Invalid PIN',
      'btn-access-portal': 'Access Guard Portal',
      'search-visitor': 'Search Visitor',
      'search-subtitle': 'Enter the visitor number to look up',
      'placeholder-search': 'Enter visitor number (e.g. V-20250622-001)',
      'btn-look-up': 'Look Up',
      'search-hint': 'Enter a visitor number (e.g. V-20250622-001)',
      'status-pending': 'Pending Entry',
      'status-checked-in': 'Checked In',
      'status-rejected': 'Rejected',
      'status-signed-out': 'Signed Out',
      'identity-info': 'Identity Information',
      'label-full-name': 'Full Name',
      'label-id-number': 'ID Number',
      'label-company': 'Company',
      'label-visitation-date': 'Visitation Date',
      'label-phone': 'Phone',
      'label-card-number': 'Card Number',
      'photo-verification': 'Photo Verification',
      'label-id-photo': 'ID Photo',
      'label-selfie': 'Selfie',
      'tap-photo-enlarge': 'Tap photo to enlarge',
      'btn-verify-checkin': 'Verify & Check-in',
      'btn-sign-out': 'Sign Out',
      'btn-reject': 'Reject',
      'already-processed': 'This visitor has already been processed.',
      'prev-rejected': 'This registration was previously rejected. (Status: Rejected)',
      'already-signed-out': 'This visitor has already signed out. (Status: Signed Out)',
      'already-checked-in': 'This visitor has already checked in. (Status: Checked In)',
      // Not Found
      'visitor-not-found': 'Visitor Not Found',
      'not-found-message': 'No registration found for this number.',
      'not-found-hint': 'Please check the number and try again.',
      'btn-try-again': 'Try Again',
      'request-timed-out': 'Request timed out. Please check your connection.',
      'make-sure-connection': 'Make sure you have an internet connection and try again.',
      'unexpected-server-response': 'Unexpected server response. Please try again.',
      'network-error': 'Network error. Please check your connection.',
      'tap-try-again-retry': 'Tap "Try Again" to retry.',
      // Success states
      'checkin-successful': 'Check-In Successful!',
      'has-been-checked-in': 'has been checked in.',
      'checked-in-at': 'Checked in at:',
      'visitor': 'Visitor:',
      'access-card': 'Access Card',
      'card-number': 'Card Number',
      'show-qr-at-gate': 'Show this QR code at the gate reader for entry',
      'no-card-available': 'No card available — notify admin to restock card pool.',
      'btn-check-in-another': '✅ Check In Another Visitor',
      // Rejected state
      'registration-rejected': 'Registration Rejected',
      'has-been-rejected': 'has been marked as rejected.',
      'rejected-at': 'Rejected at:',
      'btn-back-to-search': '↩ Back to Search',
      // Signed Out state
      'visitor-signed-out': 'Visitor Signed Out',
      'has-been-signed-out': 'has been signed out.',
      'signed-out-at': 'Signed out at:',
      // OR divider
      'or-divider': 'OR',
      // Today's Visitors
      'todays-visitors': "Today's Visitors",
      'todays-subtitle': "Quick access to today's pre-registrations",
      'filter-all': 'All',
      'filter-pending': 'Pending',
      'filter-checked-in': 'Checked In',
      'filter-done': 'Done',
      'filter-rejected': 'Rej.',
      'placeholder-filter': 'Filter by name or number...',
      'no-pending-visitors': 'No pending visitors',
      'todays-empty-subtext': 'Visitors who pre-register today will appear here.',
      'loading-visitors': 'Loading visitors...',
      'btn-view-verify': 'View & Verify',
      'btn-check-in': 'Check In',
      'btn-sign-out': 'Sign Out',
      // Bulk sign-out
      'sign-out-selected': 'Sign Out Selected',
      'bulk-sign-out': 'Bulk Sign Out',
      'sign-out-all': 'Sign Out All',
      'signing-out-visitors': 'Signing out visitors...',
      // Confirm dialogs
      'confirm-checkin': 'Confirm Check-In',
      'confirm-rejection': 'Confirm Rejection',
      'confirm-sign-out': 'Confirm Sign Out',
      'confirm-checkin-msg': 'Are you sure you want to check in',
      'confirm-reject-msg': 'Are you sure you want to reject',
      'confirm-signout-msg': 'Are you sure you want to sign out',
      'confirm-action-checkin': 'Confirm Check-In',
      'confirm-action-reject': 'Confirm Reject',
      'confirm-action-signout': 'Confirm Sign Out',
      'reason-optional': 'Reason (optional):',
      'placeholder-reason': 'e.g. ID does not match visitor',
      'btn-confirm': 'Confirm',
      'btn-cancel': 'Cancel',
      // Inline confirm
      'check-in-this-visitor': 'Check in this visitor?',
      'check-in': 'Check in',
      // Loading
      'looking-up-visitor': 'Looking up visitor...',
      'still-searching': 'Still searching...',
      'processing': 'Processing...',
      'wait-update-record': 'Please wait while we update the record',
      // Error
      'an-error-occurred': 'An error occurred.',
      // Privacy footer
      'secured-encrypted': 'Secured & encrypted via HTTPS',
      // Lightbox
      'close-photo-viewer': 'Close photo viewer',
      'previous-photo': 'Previous photo',
      'next-photo': 'Next photo',
      // Status labels in today visitor cards
      'label-pending': 'Pending',
      'label-checked-in': 'Checked In',
      'label-done': 'Done',
      'label-rejected': 'Rejected',
      'signed-out': 'Signed Out',
      'card': 'Card:',
      'signed-out-at-time': 'Signed Out:',
      // --- report.html (Reports) ---
      'title-report': 'LITEVM — Visitor Reports',
      'header-reports': 'LITEVM — Reports',
      'reports': 'Visitor Reports',
      'pin-reports': '🔒 LITEVM Reports',
      'enter-pin-continue': 'Enter PIN to continue',
      'incorrect-pin': 'Incorrect PIN',
      'report-settings': 'Report Settings',
      'select-date-range': 'Select date range and generate visitor reports',
      'from': 'From:',
      'to': 'To:',
      'preset-today': 'Today',
      'preset-yesterday': 'Yesterday',
      'preset-7days': '7 Days',
      'preset-month': 'This Month',
      'btn-generate-report': 'Generate Report',
      'btn-export-csv': '📥 CSV',
      'btn-print-pdf': '🖨️ Print / PDF',
      'hide-photos-export': 'Hide photos in export',
      // Report Results
      'report-results': 'Report Results',
      'total': 'Total:',
      'pending-count': 'Pending:',
      'checked-in-count': 'Checked In:',
      'signed-out-count': 'Signed Out:',
      'no-results': 'No visitors found for this date range.',
      'placeholder-search-report': '🔍 Search name, company, or visitor number...',
      'all-statuses': 'All Statuses',
      'status-registered': 'Registered',
      'status-checked-in': 'Checked In',
      'status-signed-out': 'Signed Out',
      'loading-report': 'Generating report...',
      'loading': 'Loading...',
      'show': 'Show',
      'hide': 'Hide',
      'page-of': 'Page',
      'of': 'of',
      'btn-prev': '← Prev',
      'btn-next': 'Next →',
      'table-num': '#',
      'table-visitor': 'Visitor #',
      'table-name': 'Name',
      'table-company': 'Company',
      'table-destination': 'Destination',
      'table-date': 'Date',
      'table-status': 'Status',
      'table-sign-in': 'Sign-In',
      'table-sign-out': 'Sign-Out',
      // CSV headers
      'csv-visitor': 'Visitor #',
      'csv-full-name': 'Full Name',
      'csv-id-number': 'ID Number',
      'csv-company': 'Company',
      'csv-destination': 'Destination',
      'csv-visitation-date': 'Visitation Date',
      'csv-phone': 'Phone',
      'csv-email': 'Email',
      'csv-status': 'Status',
      'csv-sign-in': 'Sign-In',
      'csv-sign-out': 'Sign-Out',
      // Report errors
      'err-select-date-range': 'Please select date range',
      'err-start-before-end': 'Start date must be before end date',
      'err-invalid-server-response': 'Invalid server response',
      'err-request-failed': 'Request failed',
      'err-request-timed-out': 'Request timed out. Try a narrower date range.',
      'err-network-error': 'Network error:',
      // Bulk progress
      'signed-out': 'signed out',
      'skipped': 'skipped',
      'failed': 'failed',
      'cards-released': 'Cards released.',
      'no-visitors-signed-out': 'No visitors were signed out',
      'bulk-signout-failed': 'Bulk sign-out failed',
      // misc
      'nav-guard-portal': '🔙 Guard Portal',
      'visitors': 'visitors',
    },

    id: {
      // --- index.html (Registration) ---
      'title-register': 'LITEVM — Pendaftaran Pengunjung',
      'header-title-register': 'Pendaftaran Pengunjung',
      'header-subtitle-register': 'Prapendaftaran untuk masuk cepat',
      'step-details': 'Data',
      'step-photos': 'Foto',
      'step-submit': 'Kirim',
      'your-details': 'Data Anda',
      'your-details-subtitle': 'Silakan isi informasi Anda di bawah ini',
      'label-full-name': 'Nama Lengkap',
      'label-id-number': 'KTP / Nomor Paspor',
      'label-company': 'Nama Perusahaan',
      'label-destination': 'Tujuan',
      'label-visitation-date': 'Tanggal Kunjungan',
      'label-phone': 'Nomor Handphone',
      'label-email': 'Alamat Email',
      'placeholder-full-name': 'Contoh: Ahmad bin Ismail',
      'placeholder-id-number': 'Contoh: 880101-01-1234',
      'placeholder-company': 'Contoh: PT ABC Sdn Bhd',
      'placeholder-destination-loading': 'Memuat tujuan...',
      'placeholder-destination-select': 'Pilih tujuan',
      'placeholder-phone': 'Contoh: +62 812-3456 7890',
      'placeholder-email': 'Contoh: ahmad@example.com',
      'hint-destination': 'Kantor mana yang Anda kunjungi hari ini?',
      'hint-visitation-date': 'Pilih tanggal kunjungan Anda',
      'hint-phone': 'Anda akan menerima nomor pengunjung melalui telepon',
      'btn-continue-photos': 'Lanjut → Foto',
      'btn-subtitle-fill': '(isi semua kolom untuk melanjutkan)',
      'btn-subtitle-tap': 'Ketuk untuk melanjutkan',
      // Step 2 - Photos
      'header-capture-photos': 'Ambil Foto',
      'take-your-photos': 'Ambil Foto Anda',
      'take-your-photos-subtitle': 'Silakan ambil foto dokumen ID dan selfie Anda. Keduanya diperlukan untuk masuk.',
      'camera-denied': 'Akses kamera ditolak. Gunakan opsi unggah sebagai gantinya.',
      'label-id-photo': 'Foto KTP / Paspor',
      'label-selfie': 'Selfie (Foto Wajah)',
      'tap-to-capture': 'Ketuk untuk mengambil',
      'initializing-camera': 'Menginisialisasi kamera...',
      'btn-open-camera': 'Buka Kamera',
      'btn-upload': 'Unggah',
      'btn-capture': 'Ambil',
      'btn-retake': 'Ulang',
      'btn-cancel': 'Batal',
      'processing-photo': 'Memproses foto...',
      'btn-review-submit': 'Tinjau & Kirim',
      'btn-subtitle-capture': '(ambil kedua foto untuk melanjutkan)',
      'btn-subtitle-review': 'Tinjau informasi Anda',
      // Step 3 - Review
      'header-review-submit': 'Tinjau & Kirim',
      'confirm-your-details': 'Konfirmasi Data Anda',
      'confirm-details-subtitle': 'Silakan tinjau semua informasi sebelum mengirim.',
      'personal-information': 'Informasi Pribadi',
      'review-label-name': 'Nama Lengkap',
      'review-label-id': 'KTP / Paspor',
      'review-label-company': 'Perusahaan',
      'review-label-destination': 'Tujuan',
      'review-label-visitation-date': 'Tanggal Kunjungan',
      'review-label-phone': 'Telepon',
      'review-label-email': 'Email',
      'section-photos': 'Foto',
      'review-label-id-photo': 'Foto KTP',
      'review-label-selfie': 'Selfie',
      'not-captured': 'Belum diambil',
      'captured': 'Telah diambil ✓',
      'consent-notice': 'Dengan mengirimkan, Anda menyetujui data dan foto Anda disimpan untuk keperluan manajemen pengunjung.',
      'btn-submit-registration': 'Kirim Pendaftaran',
      // Step 4 - Confirmation
      'registration-complete': 'Pendaftaran Selesai!',
      'registration-complete-subtitle': 'Data Anda telah dikirim dan dicatat.',
      'show-qr-at-entrance': 'Tunjukkan kode QR ini di pintu masuk',
      'your-visitor-number': 'Nomor Pengunjung Anda',
      'email-confirmation': 'Konfirmasi Email',
      'email-confirmation-text': 'Email konfirmasi akan dikirim ke kotak masuk Anda sebentar lagi.',
      'next-steps': 'Langkah Selanjutnya',
      'next-step-1': 'Periksa email Anda dalam 2 menit',
      'next-step-2': 'Tunjukkan kode QR di pintu masuk',
      'next-step-3': 'Petugas akan memverifikasi dan memberikan akses',
      'data-encrypted-secure': 'Data Anda dienkripsi dan aman',
      'btn-done': 'Selesai',
      // Loading & Error
      'submitting': 'Mengirim...',
      'submitting-subtext': 'Harap tunggu sementara kami memproses pendaftaran Anda',
      'submission-failed': 'Pengiriman Gagal',
      'error-occurred': 'Terjadi kesalahan. Silakan coba lagi.',
      'btn-retry': 'Coba Lagi',
      'btn-cancel-error': 'Batal',
      // Validation
      'err-full-name': 'Silakan masukkan nama lengkap Anda',
      'err-id-number': 'Silakan masukkan nomor KTP atau paspor yang valid',
      'err-id-format': 'Hanya huruf, angka, dan tanda hubung yang diizinkan',
      'err-company': 'Silakan masukkan nama perusahaan Anda',
      'err-phone': 'Silakan masukkan nomor telepon yang valid (contoh: +62 812-3456 7890)',
      'err-email-empty': 'Silakan masukkan alamat email Anda',
      'err-email-format': 'Silakan masukkan alamat email yang valid',
      'err-destination': 'Silakan pilih tujuan',
      'err-visitation-date': 'Silakan pilih tanggal kunjungan',
      'err-visitation-past': 'Tanggal kunjungan tidak boleh di masa lalu',
      // Destinations
      'loading-destinations': 'Memuat tujuan...',
      'no-destinations': 'Tidak ada tujuan tersedia',
      'no-destinations-configured': 'Tidak ada tujuan yang dikonfigurasi',
      'retrying-destinations': 'Mencoba lagi...',
      'failed-to-load': 'Gagal memuat',
      'failed-load-destinations': 'Gagal memuat tujuan. ',
      'tap-to-retry': 'Ketuk untuk mencoba lagi',
      // Offline
      'offline-message': 'Anda offline. Harap periksa koneksi Anda.',
      // Privacy
      'privacy-footer': 'Informasi Anda disimpan dengan aman. Data hanya digunakan untuk keperluan manajemen pengunjung.',
      // Photo error messages
      'photo-too-large': 'Foto terlalu besar. Ukuran maksimum adalah 5MB.',
      'err-capture-both-photos': 'Silakan ambil kedua foto sebelum mengirim.',
      'err-fill-all-fields': 'Silakan isi semua kolom yang diperlukan dengan benar.',
      'err-offline-submit': 'Anda offline. Harap periksa koneksi internet Anda dan coba lagi.',
      'err-api-not-configured': 'Endpoint API belum dikonfigurasi. Hubungi administrator.',
      'err-unexpected-response': 'Respons tidak terduga dari server. Silakan coba lagi.',
      'err-submission-failed': 'Pengiriman gagal. Silakan coba lagi.',
      'err-request-timeout': 'Permintaan habis waktu. Harap periksa koneksi Anda dan coba lagi.',
      'err-connection-failed': 'Koneksi gagal. Ini mungkin pembatasan keamanan browser. Coba lagi atau gunakan browser lain.',
      'err-network': 'Kesalahan jaringan. Harap periksa koneksi Anda dan coba lagi.',
      'err-card-not-found': 'Nomor kartu tidak ditemukan.',
      'err-no-match-today': 'Tidak ada kecocokan untuk hari ini. Pastikan nomornya benar.',
      'err-visitor-number-format': 'Nomor pengunjung mengikuti format V-YYYYMMDD-NNN (contoh: V-20250622-001). Harap periksa nomor dan coba lagi.',
      'err-failed-update-status': 'Gagal memperbarui status. Silakan coba lagi.',
      'err-failed-load-destinations': 'Gagal memuat tujuan.',
      // --- verify.html (Guard Portal) ---
      'title-verify': 'LITEVM — Portal Petugas',
      'header-title-verify': 'LITEVM — Portal Petugas',
      'header-subtitle-verify': 'Verifikasi check-in pengunjung',
      'nav-visitor-registration': '← Pendaftaran Pengunjung',
      'nav-reports': '📋 Laporan',
      'guard-portal': 'Portal Petugas',
      'enter-pin': 'Masukkan PIN untuk mengakses',
      'placeholder-pin': 'Masukkan PIN',
      'invalid-pin': 'PIN Salah',
      'btn-access-portal': 'Akses Portal Petugas',
      'search-visitor': 'Cari Pengunjung',
      'search-subtitle': 'Masukkan nomor pengunjung untuk dicari',
      'placeholder-search': 'Masukkan nomor pengunjung (contoh: V-20250622-001)',
      'btn-look-up': 'Cari',
      'search-hint': 'Masukkan nomor pengunjung (contoh: V-20250622-001)',
      'status-pending': 'Menunggu Masuk',
      'status-checked-in': 'Sudah Check-In',
      'status-rejected': 'Ditolak',
      'status-signed-out': 'Sudah Keluar',
      'identity-info': 'Informasi Identitas',
      'label-full-name': 'Nama Lengkap',
      'label-id-number': 'Nomor KTP',
      'label-company': 'Perusahaan',
      'label-visitation-date': 'Tanggal Kunjungan',
      'label-phone': 'Telepon',
      'label-card-number': 'Nomor Kartu',
      'photo-verification': 'Verifikasi Foto',
      'label-id-photo': 'Foto KTP',
      'label-selfie': 'Selfie',
      'tap-photo-enlarge': 'Ketuk foto untuk memperbesar',
      'btn-verify-checkin': 'Verifikasi & Check-In',
      'btn-sign-out': 'Keluar',
      'btn-reject': 'Tolak',
      'already-processed': 'Pengunjung ini sudah diproses.',
      'prev-rejected': 'Pendaftaran ini sebelumnya ditolak. (Status: Ditolak)',
      'already-signed-out': 'Pengunjung ini sudah keluar. (Status: Sudah Keluar)',
      'already-checked-in': 'Pengunjung ini sudah check-in. (Status: Sudah Check-In)',
      // Not Found
      'visitor-not-found': 'Pengunjung Tidak Ditemukan',
      'not-found-message': 'Tidak ada pendaftaran ditemukan untuk nomor ini.',
      'not-found-hint': 'Harap periksa nomor dan coba lagi.',
      'btn-try-again': 'Coba Lagi',
      'request-timed-out': 'Permintaan habis waktu. Harap periksa koneksi Anda.',
      'make-sure-connection': 'Pastikan Anda memiliki koneksi internet dan coba lagi.',
      'unexpected-server-response': 'Respons server tidak terduga. Silakan coba lagi.',
      'network-error': 'Kesalahan jaringan. Harap periksa koneksi Anda.',
      'tap-try-again-retry': 'Ketuk "Coba Lagi" untuk mencoba ulang.',
      // Success states
      'checkin-successful': 'Check-In Berhasil!',
      'has-been-checked-in': 'telah check-in.',
      'checked-in-at': 'Check-In pada:',
      'visitor': 'Pengunjung:',
      'access-card': 'Kartu Akses',
      'card-number': 'Nomor Kartu',
      'show-qr-at-gate': 'Tunjukkan kode QR ini di pembaca pintu untuk masuk',
      'no-card-available': 'Tidak ada kartu tersedia — beri tahu admin untuk mengisi ulang stok kartu.',
      'btn-check-in-another': '✅ Check-In Pengunjung Lain',
      // Rejected state
      'registration-rejected': 'Pendaftaran Ditolak',
      'has-been-rejected': 'telah ditandai sebagai ditolak.',
      'rejected-at': 'Ditolak pada:',
      'btn-back-to-search': '↩ Kembali ke Pencarian',
      // Signed Out state
      'visitor-signed-out': 'Pengunjung Keluar',
      'has-been-signed-out': 'telah keluar.',
      'signed-out-at': 'Keluar pada:',
      // OR divider
      'or-divider': 'ATAU',
      // Today's Visitors
      'todays-visitors': 'Pengunjung Hari Ini',
      'todays-subtitle': 'Akses cepat ke prapendaftaran hari ini',
      'filter-all': 'Semua',
      'filter-pending': 'Menunggu',
      'filter-checked-in': 'Check-In',
      'filter-done': 'Selesai',
      'filter-rejected': 'Tolak',
      'placeholder-filter': 'Filter berdasarkan nama atau nomor...',
      'no-pending-visitors': 'Tidak ada pengunjung menunggu',
      'todays-empty-subtext': 'Pengunjung yang mendaftar hari ini akan muncul di sini.',
      'loading-visitors': 'Memuat pengunjung...',
      'btn-view-verify': 'Lihat & Verifikasi',
      'btn-check-in': 'Check-In',
      'btn-sign-out': 'Keluar',
      // Bulk sign-out
      'sign-out-selected': 'Keluar yang Dipilih',
      'bulk-sign-out': 'Keluar Massal',
      'sign-out-all': 'Keluar Semua',
      'signing-out-visitors': 'Memproses keluar pengunjung...',
      // Confirm dialogs
      'confirm-checkin': 'Konfirmasi Check-In',
      'confirm-rejection': 'Konfirmasi Penolakan',
      'confirm-sign-out': 'Konfirmasi Keluar',
      'confirm-checkin-msg': 'Apakah Anda yakin ingin check-in',
      'confirm-reject-msg': 'Apakah Anda yakin ingin menolak',
      'confirm-signout-msg': 'Apakah Anda yakin ingin mengeluarkan',
      'confirm-action-checkin': 'Konfirmasi Check-In',
      'confirm-action-reject': 'Konfirmasi Tolak',
      'confirm-action-signout': 'Konfirmasi Keluar',
      'reason-optional': 'Alasan (opsional):',
      'placeholder-reason': 'Contoh: KTP tidak sesuai dengan pengunjung',
      'btn-confirm': 'Konfirmasi',
      'btn-cancel': 'Batal',
      // Inline confirm
      'check-in-this-visitor': 'Check-In pengunjung ini?',
      'check-in': 'Check-In',
      // Loading
      'looking-up-visitor': 'Mencari pengunjung...',
      'still-searching': 'Masih mencari...',
      'processing': 'Memproses...',
      'wait-update-record': 'Harap tunggu sementara kami memperbarui catatan',
      // Error
      'an-error-occurred': 'Terjadi kesalahan.',
      // Privacy footer
      'secured-encrypted': 'Aman & terenkripsi via HTTPS',
      // Lightbox
      'close-photo-viewer': 'Tutup penampil foto',
      'previous-photo': 'Foto sebelumnya',
      'next-photo': 'Foto berikutnya',
      // Status labels in today visitor cards
      'label-pending': 'Menunggu',
      'label-checked-in': 'Check-In',
      'label-done': 'Selesai',
      'label-rejected': 'Ditolak',
      'signed-out': 'Keluar',
      'card': 'Kartu:',
      'signed-out-at-time': 'Keluar:',
      // --- report.html (Reports) ---
      'title-report': 'LITEVM — Laporan Pengunjung',
      'header-reports': 'LITEVM — Laporan',
      'reports': 'Laporan Pengunjung',
      'pin-reports': '🔒 Laporan LITEVM',
      'enter-pin-continue': 'Masukkan PIN untuk melanjutkan',
      'incorrect-pin': 'PIN Salah',
      'report-settings': 'Pengaturan Laporan',
      'select-date-range': 'Pilih rentang tanggal dan buat laporan pengunjung',
      'from': 'Dari:',
      'to': 'Ke:',
      'preset-today': 'Hari Ini',
      'preset-yesterday': 'Kemarin',
      'preset-7days': '7 Hari',
      'preset-month': 'Bulan Ini',
      'btn-generate-report': 'Buat Laporan',
      'btn-export-csv': '📥 CSV',
      'btn-print-pdf': '🖨️ Cetak / PDF',
      'hide-photos-export': 'Sembunyikan foto di ekspor',
      // Report Results
      'report-results': 'Hasil Laporan',
      'total': 'Total:',
      'pending-count': 'Menunggu:',
      'checked-in-count': 'Check-In:',
      'signed-out-count': 'Keluar:',
      'no-results': 'Tidak ada pengunjung ditemukan untuk rentang tanggal ini.',
      'placeholder-search-report': '🔍 Cari nama, perusahaan, atau nomor pengunjung...',
      'all-statuses': 'Semua Status',
      'status-registered': 'Terdaftar',
      'status-checked-in': 'Check-In',
      'status-signed-out': 'Keluar',
      'loading-report': 'Menghasilkan laporan...',
      'loading': 'Memuat...',
      'show': 'Tampilkan',
      'hide': 'Sembunyikan',
      'page-of': 'Halaman',
      'of': 'dari',
      'btn-prev': '← Sebelumnya',
      'btn-next': 'Berikutnya →',
      'table-num': '#',
      'table-visitor': 'Pengunjung #',
      'table-name': 'Nama',
      'table-company': 'Perusahaan',
      'table-destination': 'Tujuan',
      'table-date': 'Tanggal',
      'table-status': 'Status',
      'table-sign-in': 'Masuk',
      'table-sign-out': 'Keluar',
      // CSV headers
      'csv-visitor': 'Pengunjung #',
      'csv-full-name': 'Nama Lengkap',
      'csv-id-number': 'Nomor KTP',
      'csv-company': 'Perusahaan',
      'csv-destination': 'Tujuan',
      'csv-visitation-date': 'Tanggal Kunjungan',
      'csv-phone': 'Telepon',
      'csv-email': 'Email',
      'csv-status': 'Status',
      'csv-sign-in': 'Masuk',
      'csv-sign-out': 'Keluar',
      // Report errors
      'err-select-date-range': 'Silakan pilih rentang tanggal',
      'err-start-before-end': 'Tanggal mulai harus sebelum tanggal akhir',
      'err-invalid-server-response': 'Respons server tidak valid',
      'err-request-failed': 'Permintaan gagal',
      'err-request-timed-out': 'Permintaan habis waktu. Coba rentang tanggal yang lebih sempit.',
      'err-network-error': 'Kesalahan jaringan:',
      // Bulk progress
      'signed-out': 'keluar',
      'skipped': 'dilewati',
      'failed': 'gagal',
      'cards-released': 'Kartu dirilis.',
      'no-visitors-signed-out': 'Tidak ada pengunjung yang dikeluarkan',
      'bulk-signout-failed': 'Pengeluaran massal gagal',
      // misc
      'nav-guard-portal': '🔙 Portal Petugas',
      'visitors': 'pengunjung',
    }
  };

  // Set up App with language helpers (before page-specific JS overwrites it)
  window.App = window.App || {};
  window.App._lang = (typeof CONFIG !== 'undefined' && CONFIG.DEFAULT_LANG) || 'en';

  window.App.t = function (key) {
    var map = LANG[window.App._lang] || LANG.en;
    return map[key] !== undefined ? map[key] : (LANG.en[key] !== undefined ? LANG.en[key] : key);
  };

  window.App.setLang = function (lang) {
    if (lang !== 'en' && lang !== 'id') return;
    window.App._lang = lang;
    window.App.render();
    // Update toggle button text
    var btn = document.querySelector('.lang-toggle');
    if (btn) btn.textContent = lang === 'en' ? 'ID' : 'EN';
  };

  window.App.render = function () {
    // Update all data-i18n elements
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      el.textContent = window.App.t(key);
    });
    // Update all data-i18n-placeholder elements
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder');
      el.placeholder = window.App.t(key);
    });
    // Update title
    var titleKey = document.querySelector('title');
    if (titleKey && titleKey.getAttribute('data-i18n')) {
      titleKey.textContent = window.App.t(titleKey.getAttribute('data-i18n'));
    }
    // Update meta description
    var metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc && metaDesc.getAttribute('data-i18n')) {
      metaDesc.setAttribute('content', window.App.t(metaDesc.getAttribute('data-i18n')));
    }
  };

})();
